# Generated by Django 5.0.3 on 2024-03-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0002_alter_room_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="places",
            field=models.PositiveIntegerField(max_length=2),
        ),
    ]
