# Generated by Django 5.0.3 on 2024-03-28 11:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0004_alter_room_places"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="room",
            options={"verbose_name": "Комнаты", "verbose_name_plural": "Комнаты"},
        ),
    ]
