# Generated by Django 5.0.3 on 2024-03-29 12:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0006_reservation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reservation",
            old_name="Въезд",
            new_name="check_in",
        ),
        migrations.RenameField(
            model_name="reservation",
            old_name="Выезд",
            new_name="check_out",
        ),
    ]
