# Generated by Django 5.0.3 on 2024-03-29 17:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0007_rename_въезд_reservation_check_in_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="is_booked",
        ),
    ]
